In [1]:
import numpy as np
import pandas as pd

In [3]:
empty_dataframe = pd.DataFrame()

In [5]:
print(empty_dataframe)

Empty DataFrame
Columns: []
Index: []

In [7]:
political_figures = ['Mustafa Kemal Ataturk', 'Franklin D. Roosevelt', 'Winston Churchill', 'Charles de Gaulle',
                     'Jawaharlal Nehru', 'Nelson Mandela', 'Deng Xiaoping']

In [9]:
df_from_list = pd.DataFrame(political_figures)
df_from_list

                       0
0  Mustafa Kemal Ataturk
1  Franklin D. Roosevelt
2      Winston Churchill
3      Charles de Gaulle
4       Jawaharlal Nehru
5         Nelson Mandela
6          Deng Xiaoping

In [11]:
countries = ['Turkey', 'USA', 'UK', 'France', 'India', 'South Africa', 'China']

In [13]:
politicians_tuples = list(zip(political_figures, countries))
politicians_tuples

[('Mustafa Kemal Ataturk', 'Turkey'),
 ('Franklin D. Roosevelt', 'USA'),
 ('Winston Churchill', 'UK'),
 ('Charles de Gaulle', 'France'),
 ('Jawaharlal Nehru', 'India'),
 ('Nelson Mandela', 'South Africa'),
 ('Deng Xiaoping', 'China')]

In [15]:
df_from_list_of_tuples = pd.DataFrame(politicians_tuples)
df_from_list_of_tuples

                       0             1
0  Mustafa Kemal Ataturk        Turkey
1  Franklin D. Roosevelt           USA
2      Winston Churchill            UK
3      Charles de Gaulle        France
4       Jawaharlal Nehru         India
5         Nelson Mandela  South Africa
6          Deng Xiaoping         China

In [17]:
df_from_list_of_tuples = pd.DataFrame(politicians_tuples, columns=['Politician Name', 'Country'])
df_from_list_of_tuples

         Politician Name       Country
0  Mustafa Kemal Ataturk        Turkey
1  Franklin D. Roosevelt           USA
2      Winston Churchill            UK
3      Charles de Gaulle        France
4       Jawaharlal Nehru         India
5         Nelson Mandela  South Africa
6          Deng Xiaoping         China

In [19]:
political_figures = ['Mustafa Kemal Ataturk', 'Franklin D. Roosevelt', 'Winston Churchill', 'Charles de Gaulle',
                     'Jawaharlal Nehru', 'Nelson Mandela', 'Deng Xiaoping']
countries = ['Turkey', 'USA', 'UK', 'France', 'India', 'South Africa', 'China']

In [21]:
politicians_dict = {'Politician Name': pd.Series(political_figures),
                    'Country': pd.Series(countries)}

In [25]:
politicians_df = pd.DataFrame(politicians_dict)
politicians_df

         Politician Name       Country
0  Mustafa Kemal Ataturk        Turkey
1  Franklin D. Roosevelt           USA
2      Winston Churchill            UK
3      Charles de Gaulle        France
4       Jawaharlal Nehru         India
5         Nelson Mandela  South Africa
6          Deng Xiaoping         China

In [27]:
politicians_df.to_csv('datasets/politicians.csv', index=False)

In [29]:
politicians_df_from_file = pd.read_csv('datasets/politicians.csv')
politicians_df_from_file

         Politician Name       Country
0  Mustafa Kemal Ataturk        Turkey
1  Franklin D. Roosevelt           USA
2      Winston Churchill            UK
3      Charles de Gaulle        France
4       Jawaharlal Nehru         India
5         Nelson Mandela  South Africa
6          Deng Xiaoping         China

In [31]:
avocado_data = pd.read_csv('datasets/avocado.csv')
avocado_data

,Index,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18244,7,2018-02-04,1.63,17074.83,2046.96,1529.20,0.00,13498.67,13066.82,431.85,0.0,organic,2018,WestTexNewMexico
18245,8,2018-01-28,1.71,13888.04,1191.70,3431.50,0.00,9264.84,8940.04,324.80,0.0,organic,2018,WestTexNewMexico
18246,9,2018-01-21,1.87,13766.76,1191.92,2452.79,727.94,9394.11,9351.80,42.31,0.0,organic,2018,WestTexNewMexico
18247,10,2018-01-14,1.93,16205.22,1527.63,2981.04,727.01,10969.54,10919.54,50.00,0.0,organic,2018,WestTexNewMexico
18248,11,2018-01-07,1.62,17489.58,2894.77,2356.13,224.53,12014.15,11988.14,26.01,0.0,organic,2018,WestTexNewMexico